version: 2

project_name: crac

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows
      - darwin
    id: crac
    binary: crac
    main: ./cmd/crac
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "crac_checksums.txt"

nfpms:
  - vendor: crac
    homepage: https://github.com/ssuf1998dev/container-registry-as-cache
    maintainer: ssuf1998dev <ssuf1998dev@126.com>
    section: golang
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
